
export const PRODUCTION_ORIGINS = [
    'https://internal.wayru.co',
    'https://api.wayru.co',
    'https://api.wayru.tech',
    'https://api.prod-2.wayru.tech',
    'https://api.testnet.wayru.tech',
    'https://api.develop.wayru.co',
    'http://localhost:8080',
    'https://api.coingecko.com/api/v3/coins/algorand',
    'https://api.coingecko.com/api/v3/coins/markets',
    'https://dashboard-backend-upload-dev.s3.us-east-2.amazonaws.com',
    'https://www.testnet.wayru.io',
    'https://testnet.wayru.io',
    'https://operator.wayru.io',
    'https://www.partner.wayru.io',
    'https://partner.wayru.io',
    'https://www.app.wayru.net/',
    'https://app.wayru.net/',
    'https://wifi.api.wayru.tech/',
    'https://wifi.api.internal.wayru.tech/',
    'https://portal.wayru.io',
    'https://portal.wayru.tech',
    'https://portal.internal.wayru.tech',
    'https://airblocks-club-git-feat-test-operators-wayru.vercel.app',
]