const errornIndex = 'SSS-'

export const REQUEST_TRANSACTION_ERROR_CODES = {
    REQUEST_TRANSACTION_ERROR_CODE: errornIndex + '001',
    REQUEST_TRANSACTION_SUCCESS_CODE: errornIndex + '002',
    REQUEST_INITIALIZE_NFNODE_ERROR_CODE: errornIndex + '003',
    REQUEST_CLAIM_REWARD_ERROR_CODE: errornIndex + '004',
    REQUEST_CLAIM_REWARD_SUCCESS_CODE: errornIndex + '005',
    REQUEST_CLAIM_REWARD_PARAMS_ERROR_CODE: errornIndex + '006',
    REQUEST_CLAIM_REWARD_PREPARED_ACCOUNTS_ERROR_CODE: errornIndex + '007',
    REQUEST_UPDATE_HOST_ERROR_CODE: errornIndex + '008',
    REQUEST_UPDATE_NFNODE_SUCCESS_CODE: errornIndex + '009',
    REQUEST_CLAIM_REWARD_INVALID_SIGNATURE_ERROR_CODE: errornIndex + '010',
    REQUEST_CLAIM_REWARD_SIGNATURE_NOT_FOUND_ERROR_CODE: errornIndex + '011',
    REQUEST_CLAIM_REWARD_INVALID_DATA_ERROR_CODE: errornIndex + '012',
    REQUEST_CLAIM_REWARD_INVALID_REWARDS_ERROR_CODE: errornIndex + '013',
    REQUEST_CLAIM_REWARD_MINER_ID_NOT_MATCH_ERROR_CODE: errornIndex + '014',
    REQUEST_CLAIM_REWARD_UPDATE_CLAIM_REWARD_HISTORY_ERROR_CODE: errornIndex + '015',
    REQUEST_INITIALIZE_NFNODE_INVALID_SIGNATURE_ERROR_CODE: errornIndex + '016',
    REQUEST_INITIALIZE_NFNODE_INVALID_DATA_ERROR_CODE: errornIndex + '017'
}